---
- hosts: k3s_cluster
  gather_facts: true
  become: true

  roles:
    - { role: geerlingguy.pip }
    - { role: ansible-role-unix-tools }
    - { role: ansible-role-download-k3s }

#- hosts: master
#  gather_facts: true
#  become: true
#  roles:
#    - {  role: ansible-role-setup-k3s/master }

#- hosts: node
#  gather_facts: true
#  become: true
#  roles:
#    - {  role: ansible-role-setup-k3s/agents }
...