---
ansible_user: vagrant
k3s_version: v1.27.1+k3s1
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]].master_host | default(groups['master'][0]) }}"
master_token: "{{ hostvars[groups['master'][0]].master_token }}"
extra_server_args: ""
extra_agent_args: ""
...